config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/conditions/temp'  => "conditions#destroy"
  get '/conditions/temp2'  => "conditions#edit"
  resources :conditions
  resources :users
  root "conditions#index"

end

app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :conditions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:show, :update]
  before_action :set_condition_destroy, only: [:destroy, :edit]
  before_action :move_to_index, except: :index

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all
#    cdays = @conditions.map{|condition| condition.cday.strftime("%Y-%m-%d")}
    cdays = @conditions.map{|condition| condition.cday}
    mps = @conditions.map{|condition| condition.mp}
    tickinterval = 2
    
#    category = [1,3,5,7]
#    current_quantity = [1000,5000,3000,8000]
#    current_quantity2 = [1000,5000,3000,8000,1000,5000,3000,8000]
#    @graph = LazyHighCharts::HighChart.new('graphhhhh') do |f|
#      f.title(text: 'aaaa')
#      f.xAxis(categories: category)
#      f.series(name: 'zaiko', data: current_quantity)
#    end
#    @data_mp = LazyHighCharts::HighChart.new('mpmp') do |f2|
#      f2.chart(type: 'spline')
#      f2.title(text: 'bbb')
#      f2.xAxis(type: 'datetime', dateTimeLabelFormats: {month: '%e. %b', year: '%b'} )
#      f2.xAxis(tickinterval: tickinterval)
#      f2.series(name: 'zaiko', data: current_quantity2)
#      f2.series(name: 'day', data: cdays )
#      f2.series(name: 'MP', data: mps )
#    end
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
  end

  # GET /conditions/new
  def new
    require "json"
    require "open-uri"
    api_key = "e1a6dfa87fed1ea45838113bbdea6cf7"
    base_url = "http://api.openweathermap.org/data/2.5/weather"
    response = open(base_url + "?id=1850147&units=metric&APPID=#{api_key}")
    tenki = JSON.parse(response.read)
    @today_temperature = tenki["main"]["temp"]
    @condition = Condition.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(user_id: current_user.id, cday: condition_params[:cday], mp: condition_params[:mp], hp: condition_params[:hp], temperature: condition_params[:temperature], sleep_time: condition_params[:sleep_time],eja_times: condition_params[:eja_times],noting: condition_params[:noting])
    #Condition.create(user_id: current_user.id, cday: condition_params[:cday], mp: condition_params[:mp], hp: 2  )

    respond_to do |format|
      if @condition.save
        format.html { redirect_to "/users/#{@condition.user_id}", notice: 'Condition was successfully created.' }
    #    format.html { redirect_to @condition, notice: 'Condition was successfully created.' }
        format.json { render :show, status: :created, location: @condition }
      else
        format.html { render :new }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end

#    redirect_to "/users/#{@condition.user_id}"
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
    respond_to do |format|
      if @condition.update(condition_params)
        format.html { redirect_to @condition, notice: 'Condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @condition }
      else
        format.html { render :edit }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json

  def destroy
    @condition.destroy
    respond_to do |format|
      format.html { redirect_to conditions_url, notice: 'Condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    def set_condition_destroy
      @condition = Condition.find_by(cday: params[:day_for_delete])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition).permit(:user_id, :cday, :mp, :hp, :temperature, :whether, :sleep_time, :eja_times, :noting)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 

    require "json"
    require "open-uri"
    api_key = "e1a6dfa87fed1ea45838113bbdea6cf7"
    base_url = "http://api.openweathermap.org/data/2.5/forecast/daily"
    #response = open(base_url + "?q=Tokyo,jp&units=metric&APPID=#{api_key}")
    response = open(base_url + "?id=1850147&units=metric&APPID=#{api_key}")
    @tenki = JSON.parse(response.read)

    @user = User.find(current_user.id)
    @name = current_user.email
    #@today_mp = current_user.conditions.order(:cday DESC ).first.mp
    today_mp = current_user.conditions.order("cday DESC ").first.mp
    today_st = current_user.conditions.order("cday DESC ").first.sleep_time
    today_ej = current_user.conditions.order("cday DESC ").first.eja_times
    today_tk = current_user.conditions.order("cday DESC ").first.temperature
    @today_condition = choushi(today_mp)

    tomorrow_tk = @tenki["list"][1]["temp"]["day"]

    tomorrow_mp = forecast(today_mp,today_st,today_ej,today_tk,tomorrow_tk)
    @tomorrow_condition = choushi(tomorrow_mp)

#    binding.pry
#    @akashi =  JSON.pretty_generate(JSON.parse(response.read)) 
  end



  def destroy
#    @conditions = current_user.conditions.where(user_id: current_user.id) 
  end

   private
    def choushi(today_mp)
      if today_mp == 1
        today_condition = '絶不調'
      elsif today_mp == 2
        today_condition = 'ちょっと不調'
      elsif today_mp == 3
        today_condition = 'まあまあ'
      elsif today_mp == 4
        today_condition = '好調'
      elsif today_mp == 5
        today_condition = '絶好調'
      else 
        today_condition = 'よくわからない'
      end

      return today_condition

    end

    def forecast(mp,st,ej,t_toda,t_tomo)
      if st > 8.0 then
        st_add = 2
      elsif st  > 6.5
        st_add = 1
      elsif st  > 5.0
        st_add = 0
      elsif st  > 3.5
        st_add = -1
      else
        st_add = -2
      end

      tomorrow_mp =  mp + st_add - ej
      
      tomorrow_mp += 1 if ej == 0


      if (t_tomo - t_toda).abs > 8.0
        tomorrow_mp -= 1
      end

      if tomorrow_mp < 1
        tomorrow_mp = 1
      elsif tomorrow_mp > 5
        tomorrow_mp = 5
      end

      return tomorrow_mp

    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conditions/_form.html.erb
<%= form_for @condition, :html => { :class => "form-horizontal condition" } do |f| %>

  <% if @condition.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@condition.errors.count, "error") %> prohibited this condition from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @condition.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :cday, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cday, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cday) %>
  </div>
  <div class="form-group">
    <%= f.label :mp, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mp, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mp) %>
  </div>
  <div class="form-group">
    <%= f.label :hp, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :hp, :class => 'form-control' %>
    </div>
    <%=f.error_span(:hp) %>
  </div>
  <div class="form-group">
    <%= f.label :temperature, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :temperature, :class => 'form-control' %>
    </div>
    <%=f.error_span(:temperature) %>
  </div>
  <div class="form-group">
    <%= f.label :whether, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :whether, :class => 'form-control' %>
    </div>
    <%=f.error_span(:whether) %>
  </div>
  <div class="form-group">
    <%= f.label :sleep_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sleep_time, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sleep_time) %>
  </div>
  <div class="form-group">
    <%= f.label :eja_times, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :eja_times, :class => 'form-control' %>
    </div>
    <%=f.error_span(:eja_times) %>
  </div>
  <div class="form-group">
    <%= f.label :noting, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :noting, :class => 'form-control' %>
    </div>
    <%=f.error_span(:noting) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                conditions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/conditions/edit.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conditions/index.html.erb
    <br>
    <br>
    <p>　<br></p>
    <p style="text-align:center"><font size="5">世の中のやる気</font></p>


<%= line_chart [ 
  {name: "やる気" , data: Condition.pluck(:cday, :mp)} , 
  ],
 :library => {
    :hAxis => {:title => "日付", :type => "string", :baselineColor => "black"}, 
    :curveType => "function", 
    :backgroundColor => "#eee",
    :colors => ["#DC3912"]
  } 
%>


<%= line_chart [ 
  {name: "睡眠時間" , data: Condition.pluck(:cday, :sleep_time)}
   ], 
 :library => {
    :hAxis => {:title => "日付", :type => "string", :baselineColor => "black"}, 
    :curveType => "function", 
    :backgroundColor => "#fff",
    :colors => ["#3366CC"]
  } 
%>


<%= line_chart [ 
  {name: "回数" , data: Condition.pluck(:cday, :eja_times)}  
   ] , 
 :library => {
    :hAxis => {:title => "日付", :type => "string", :baselineColor => "black"}, 
    :curveType => "function", 
    :colors => ["109618"] ,
    :backgroundColor => "#eee"
  } 
%>


<%= line_chart [ 
  {name: "気温" , data: Condition.pluck(:cday, :temperature)}
   ], 
 :library => {
    :hAxis => {:title => "日付", :type => "string", :baselineColor => "black"}, 
    :curveType => "function", 
    :backgroundColor => "#fff",
    :colors => ["#990099"]
  } 
%>



<%
=begin
%>


<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:cday) %></th>
      <th><%= model_class.human_attribute_name(:mp) %></th>
      <th><%= model_class.human_attribute_name(:hp) %></th>
      <th><%= model_class.human_attribute_name(:temperature) %></th>
      <th><%= model_class.human_attribute_name(:whether) %></th>
      <th><%= model_class.human_attribute_name(:sleep_time) %></th>
      <th><%= model_class.human_attribute_name(:eja_times) %></th>
      <th><%= model_class.human_attribute_name(:noting) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= link_to condition.id, condition_path(condition) %></td>
        <td><%= condition.user_id %></td>
        <td><%= condition.cday %></td>
        <td><%= condition.mp %></td>
        <td><%= condition.hp %></td>
        <td><%= condition.temperature %></td>
        <td><%= condition.whether %></td>
        <td><%= condition.sleep_time %></td>
        <td><%= condition.eja_times %></td>
        <td><%= condition.noting %></td>
        <td><%=l condition.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_condition_path(condition), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      condition_path(condition),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_condition_path,
            :class => 'btn btn-primary' %>


<%#= line_chart Condition.group(:created_at).count %>
<%#= line_chart Condition.order('cday ASC').pluck(:cday, :mp) %>
<%#= high_chart("yyy", @graph) %>
<%#= high_chart("zzz", @data_mp) %>
<%= line_chart Condition.pluck(:cday, :mp) , min: -1, max: 6 , xtitle: "day" , ytitle: "やる気" , colors: ["pink"], library: {backgroundColor: "red"} %>
<%= line_chart Condition.pluck(:cday, :mp) , min: -1, max: 6 , xtitle: "day" , ytitle: "やる気" , colors: ["blue"], library: {backgroundColor: "#888"} %>
<%= line_chart [ {name: "mp" , data: Condition.pluck(:cday, :mp) } , {name: "気温" , data: Condition.pluck(:cday, :temperature) } ] %>
<%#= pie_chart ({"Football": 10, "Basketball": 5 }) %>
<%= column_chart [["Ftball", 10], ["Basketball", 5 ]] %>

<%
=end
%>

app/views/conditions/new.html.erb
<%- model_class = Condition -%>
<%
=begin
%>  
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<p><%= @tenki["cod"] %></p>
<%#= render :partial => 'form' %>

<p><%= @tenki["list"][0]["main"]["temp"] %></p>
<%
=end
%>  
  
<div class="contents row">
  <%= form_tag('/conditions', method: :post) do %>
    <h3>
      今日の体調を入力しよう！
    </h3>
    <input placeholder="cday" type="date" value=<%= Date.today %> name="condition[cday]" style="width:200px" required>
    <FONT size="4">　　気温</FONT>   
    <input placeholder="気温" type="number" value=<%= @today_temperature.to_i %> name="condition[temperature]" style="width:100px" required>
    <br>
    <FONT size="4">やる気　</FONT>   
    <p> 
    1:
    <input type="radio" name="condition[mp]" value="1" style="width:20px;"> 
    2:
    <input type="radio" name="condition[mp]" value="2" style="width:20px;"> 
    3: 
    <input type="radio" name="condition[mp]" value="3" checked="checked" style="width:20px;"> 
    4:
    <input type="radio" name="condition[mp]" value="4" style="width:20px;"> 
    5:
    <input type="radio" name="condition[mp]" value="5" style="width:20px;"> 
    </p>
    <FONT size="4">体力　</FONT>   
    <p> 
    1:
    <input type="radio" name="condition[hp]" value="1" style="width:20px;"> 
    2:
    <input type="radio" name="condition[hp]" value="2" style="width:20px;"> 
    3: 
    <input type="radio" name="condition[hp]" value="3" checked="checked" style="width:20px;"> 
    4:
    <input type="radio" name="condition[hp]" value="4" style="width:20px;"> 
    5:
    <input type="radio" name="condition[hp]" value="5" style="width:20px;"> 
    </p>
    <FONT size="4">睡眠時間</FONT>   
    <input placeholder="睡眠時間" type="number" value="7.0" min="0.0" max="24.0" step="0.5" name="condition[sleep_time]" style="width:100px" required>
    <br>
    <FONT size="4">回数</FONT>   
    <p> 
    0:
    <input type="radio" name="condition[eja_times]" value="0" style="width:20px;"> 
    1:
    <input type="radio" name="condition[eja_times]" value="1" style="width:20px;" checked="checked" > 
    2:
    <input type="radio" name="condition[eja_times]" value="2" style="width:20px;"> 
    3: 
    <input type="radio" name="condition[eja_times]" value="3" style="width:20px;"> 
    4:
    <input type="radio" name="condition[eja_times]" value="4" style="width:20px;"> 
    5:
    <input type="radio" name="condition[eja_times]" value="5" style="width:20px;"> 
    </p>
    <textarea cols="30" name="condition[noting]" placeholder="備考" rows="5"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

<%
=begin
%>  
<%
=end
%>  

app/views/conditions/show.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @condition.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cday) %>:</strong></dt>
  <dd><%= @condition.cday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mp) %>:</strong></dt>
  <dd><%= @condition.mp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hp) %>:</strong></dt>
  <dd><%= @condition.hp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:temperature) %>:</strong></dt>
  <dd><%= @condition.temperature %></dd>
  <dt><strong><%= model_class.human_attribute_name(:whether) %>:</strong></dt>
  <dd><%= @condition.whether %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sleep_time) %>:</strong></dt>
  <dd><%= @condition.sleep_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eja_times) %>:</strong></dt>
  <dd><%= @condition.eja_times %></dd>
  <dt><strong><%= model_class.human_attribute_name(:noting) %>:</strong></dt>
  <dd><%= @condition.noting %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              conditions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_condition_path(@condition), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              condition_path(@condition),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MpMeter2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag "//wwww.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <%#= javascript_include_tag "//wwww.google.com/jsapi" %>
  <%= javascript_include_tag "application", "chartkick" %>
  <script type="text/javascript">
    WebFontConfig = {
      google: { families: [ 'Unica+One::latin' ] }
    };
    (function() {
      var wf = document.createElement('script');
      wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
        '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
      wf.type = 'text/javascript';
      wf.async = 'true';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(wf, s);
    })();
  </script> 
</head>

  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-12"><a href="/">やる気メーター</a></h1>
    </div>
    <% if user_signed_in? %>
    <div class="header__bar row">
      <h1 class="grid-4"><a href="/users/<%= current_user.id %>">マイページ</a></h1>
      <h1 class="grid-4"><a href="/conditions/new">今日の調子を入力</a></h1>
      <h1 class="grid-4"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></h1>
    </div>
    <% else %>
    <div class="header__bar row">
        <h1 class="grid-6"><%= link_to "ログイン", new_user_session_path, class: 'post' %></h1>
        <h1 class="grid-6"><%= link_to "新規登録", new_user_registration_path, class: 'post' %></h1>
      </div>
    </div>
      <% end %>
    </div>
  </header>


<body>


<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>